language: android
env:
  matrix:
    - ANDROID_SDKS=android-18,sysimg-18  ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a
branches:
  only:
    - master
    - develop
android:
  components:
    - tools

    # The BuildTools version
    - build-tools-20.0.0

    # The SDK version
    - $ANDROID_SDKS

    # Additional components
    - extra-android-m2repository
script:
  - cd amalgam
  - TERM=dumb ./gradlew build test
